// week3/Practice2_react/src/App.js
import React, { useState } from 'react'; // 從 react 套件引入 useState
import './App.css'; // 引入剛才改好的 CSS

function App() {
    const [todos, setTodos] = useState([]);
    const [newTodo, setNewTodo] = useState('');

    const addTodo = () => {
        const todoText = newTodo.trim();
        if (todoText !== '') {
            setTodos([...todos, todoText]);
            setNewTodo('');
        }
    };

    const removeTodo = (index) => {
        const updatedTodos = [...todos];
        updatedTodos.splice(index, 1);
        setTodos(updatedTodos);
    };

    return (
        <div id="app">
            <h1>To-Do List (React)</h1>
            <div style={{ display: 'flex', gap: '5px' }}>
                <input
                    type="text"
                    value={newTodo}
                    onChange={(e) => setNewTodo(e.target.value)}
                    placeholder="Add a new task"
                />
                <button onClick={addTodo}>Add</button>
            </div>
            <ul>
                {todos.map((todo, index) => (
                    <li key={index}>
                        <span>{todo}</span>
                        <button onClick={() => removeTodo(index)}>Remove</button>
                    </li>
                ))}
            </ul>
        </div>
    );
}

export default App; // 導出元件讓 index.js 使用

// week3/Practice3_vue/src/App.vue
<script setup>
import { ref } from 'vue'

// 1. 定義狀態 (data)
const todos = ref([])
const newTodo = ref('')

// 2. 定義方法 (methods)
const addTodo = () => {
  const todoText = newTodo.value.trim()
  if (todoText !== '') {
    todos.value.push(todoText)
    newTodo.value = ''
  }
}

const removeTodo = (index) => {
  todos.value.splice(index, 1)
}
</script>

<template>
  <div class="todo-container">
    <h1>To-Do List (Vue 3)</h1>
    
    <div class="input-group">
      <input
        type="text"
        v-model="newTodo"
        @keyup.enter="addTodo"
        placeholder="Add a new task"
      />
      <button @click="addTodo">Add</button>
    </div>

    <ul>
      <li v-for="(todo, index) in todos" :key="index">
        <span>{{ todo }}</span>
        <button @click="removeTodo(index)" class="remove-btn">Remove</button>
      </li>
    </ul>
  </div>
</template>

<style scoped>
/* 這裡貼上你原本的 CSS */
.todo-container {
  max-width: 400px;
  margin: 50px auto;
  font-family: Arial, sans-serif;
}

h1 {
  text-align: center;
}

.input-group {
  display: flex;
  gap: 10px;
  margin-bottom: 20px;
}

input[type="text"] {
  flex: 1;
  padding: 10px;
}

ul {
  list-style: none;
  padding: 0;
}

li {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 10px 0;
  border-bottom: 1px solid #eee;
}

.remove-btn {
  background-color: #ff4d4d;
  color: white;
  border: none;
  padding: 5px 10px;
  cursor: pointer;
  border-radius: 4px;
}

.remove-btn:hover {
  background-color: #cc0000;
}
</style>
